webtalk_init -webtalk_dir C:/Users/jylee/Documents/GitHub/Xilinx_Tutorials/simulation/test00/test00.sim/sim_1/behav/xsim/xsim.dir/TB_GATE_AND_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan  7 18:28:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e2e1ffa2-bd22-4416-a1fa-d45388a42edc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3f043623fb9a430dbffc101b41e8c807" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3237625695 -regid "" -xml C:/Users/jylee/Documents/GitHub/Xilinx_Tutorials/simulation/test00/test00.sim/sim_1/behav/xsim/xsim.dir/TB_GATE_AND_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jylee/Documents/GitHub/Xilinx_Tutorials/simulation/test00/test00.sim/sim_1/behav/xsim/xsim.dir/TB_GATE_AND_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jylee/Documents/GitHub/Xilinx_Tutorials/simulation/test00/test00.sim/sim_1/behav/xsim/xsim.dir/TB_GATE_AND_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
